spring.application.name=eiips
spring.profile.active=dev

spring.config.import=aws-parameterstore:

spring.datasource.url=${invoice-service/db-url}
spring.datasource.username=${invoice-service/db-user}
spring.datasource.password=${invoice-service/password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

spring.file.upload-dir=${UPLOAD_DIR:${java.io.tmpdir}/staging-batch}
